# Interactive component

## The relationship between parents' and teachers' feeling about family-community bonds

```{r}
library(readxl)
library(tidyverse)
family<-read_rds("family")

library(parcoords)
library(webshot)
library(d3r)
family_<-family %>% mutate(t_s_disagree_percent = t_s_disagree/(t_s_disagree+t_s_agree+t_agree+t_disagree)) %>% mutate(t_disagree_percent = t_disagree/(t_s_disagree+t_s_agree+t_agree+t_disagree))%>% mutate(t_agree_percent = t_agree/(t_s_disagree+t_s_agree+t_agree+t_disagree))%>% mutate(t_s_agree_percent = t_s_agree/(t_s_disagree+t_s_agree+t_agree+t_disagree))%>% mutate(t_score = 2*t_s_agree_percent+1*t_agree_percent-1*t_disagree_percent-2*t_s_disagree_percent) %>% mutate(p_s_disagree_percent = p_s_disagree/(p_s_disagree+p_s_agree+p_agree+p_disagree)) %>% mutate(p_disagree_percent = p_disagree/(p_s_disagree+p_s_agree+p_agree+p_disagree))%>% mutate(p_agree_percent = p_agree/(p_s_disagree+p_s_agree+p_agree+p_disagree))%>% mutate(p_s_agree_percent = p_s_agree/(p_s_disagree+p_s_agree+p_agree+p_disagree))%>% mutate(p_score = 2*p_s_agree_percent+1*p_agree_percent-1*p_disagree_percent-2*p_s_disagree_percent)

family_sel = family_ %>% select(t_s_disagree_percent,t_disagree_percent,t_agree_percent,t_s_agree_percent,p_s_disagree_percent,p_disagree_percent,p_agree_percent,p_s_agree_percent)

parcoords(data = family_sel,brushMode = '1D-axes',queue = TRUE,withD3 = TRUE)
```

## The relationship between students' and teachers' feeling about student inclusion

```{r}
inclusion<-read_rds("inclusion")
inclusion_<-inclusion %>% mutate(t_s_disagree_percent = t_s_disagree/(t_s_disagree+t_s_agree+t_agree+t_disagree)) %>% mutate(t_disagree_percent = t_disagree/(t_s_disagree+t_s_agree+t_agree+t_disagree))%>% mutate(t_agree_percent = t_agree/(t_s_disagree+t_s_agree+t_agree+t_disagree))%>% mutate(t_s_agree_percent = t_s_agree/(t_s_disagree+t_s_agree+t_agree+t_disagree))%>% mutate(t_score = 2*t_s_agree_percent+1*t_agree_percent-1*t_disagree_percent-2*t_s_disagree_percent) %>% mutate(st_s_disagree_percent = st_s_disagree/(st_s_disagree+st_s_agree+st_agree+st_disagree)) %>% mutate(st_disagree_percent = st_disagree/(st_s_disagree+st_s_agree+st_agree+st_disagree))%>% mutate(st_agree_percent = st_agree/(st_s_disagree+st_s_agree+st_agree+st_disagree))%>% mutate(st_s_agree_percent = st_s_agree/(st_s_disagree+st_s_agree+st_agree+st_disagree))%>% mutate(st_score = 2*st_s_agree_percent+1*st_agree_percent-1*st_disagree_percent-2*st_s_disagree_percent)

inclusion_sel = inclusion_ %>% select(t_s_disagree_percent,t_disagree_percent,t_agree_percent,t_s_agree_percent,st_s_disagree_percent,st_disagree_percent,st_agree_percent,st_s_agree_percent)

parcoords(data = inclusion_sel,brushMode = '1D-axes',queue = TRUE,withD3 = TRUE)
```


