--- 
title: "NYC School Survey"
author: "Ziheng Ru, Zihan Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

### Introduction to NYC School Survey

Every year, all parents, all teachers, and students take the [NYC School Survey](https://infohub.nyced.org/reports/school-quality/nyc-school-survey). The survey ranks among the largest surveys of any kind ever conducted nationally. 

The NYC School Survey consists of three separate survey instruments: The “parent/guardian
survey”, the “teacher survey”, and the “student survey” (for students in grades 6 – 12 only).
To review 2021 NYC School Survey instruments, see the links below:
\
https://infohub.nyced.org/docs/default-source/default-document-library/student-instrument_08312021_accessible.pdf \

https://infohub.nyced.org/docs/default-source/default-document-library/family-instrument_083121_accessible.pdf \

https://infohub.nyced.org/docs/default-source/default-document-library/teacher-instrument_aug-2021_accessible.pdf \


Survey questions assess the community's opinions on academic expectations, communication, engagement, and safety and respect. Survey results provide insight into a school's learning environment and contribute a measure of diversification that goes beyond test scores on the Progress Report. School leaders can use survey results to better understand their own school's strengths and target areas for improvement.

The NYC School Quality Reports includes six elements -- Rigorous Instruction, Collaborative
Teachers, Supportive Environment, Effective School Leadership, Strong Family Community Ties, and Trust. The meanings of these six elements are illustrated in Chapter 2. 

### Our goal in this project
In this project, we will take a look at the NYC School Quality Reports that reflect the opinion of parents, teachers and students, and answer the questions listed below:

- What are the top 10 schools with the highest survey performance? What are their characteristics?

- What is the distribution of performance over the six components (Collaborative Teachers
Score, Effective School Leadership Score, Rigorous Instruction Score, Supportive
Environment Score, Strong Family Community Ties Score, Trust Score)? What does it imply?

- How do parents, teachers, and students rate the education experience respectively? Do teachers and students have a consensus on their survey scores? And what about the
relationship between students' and parents’ responses?

